Swap out Optim.jl NelderMead.jl
JuliaML/TableTransforms.jl pull request #155
Opened 2022-11-23 19:23 UTC by jwscook

This PR removes Optim.jl as a dependency and replaces it with [NelderMead.jl](https://github.com/jwscook/NelderMead.jl) given the context of https://github.com/jwscook/NelderMead.jl/issues/7.

A point worth noting is that the size of the simplex is taken to be the standard deviation of the starting position (or 1 in the case that the standard deviation is zero). There may be a better simplex size given the range of sensible values of $\alpha_0$; please advise.

Closes https://github.com/jwscook/NelderMead.jl/issues/7.

2022-11-23 19:29 UTC, juliohm requested changes
Thank you @jwscook for the PR ❤️ Regarding the initial guess, it is guaranteed to have norm 1. Do you have suggestions for the simplex size in this case?

2022-11-23 19:29 UTC, juliohm commented on src/TableTransforms.jl
> +using NelderMead
```suggestion
using NelderMead: optimise
```

2022-11-23 19:29 UTC, juliohm commented on src/transforms/projectionpursuit.jl
> +  minimiser
```suggestion
  res = optimise(f, α₀, iszero(l) ? one(l) : l, xtol_rel=10eps())
  first(res)
```

2022-11-23 19:29 UTC, juliohm commented on test/Project.toml
> +TableTransforms = "0d432bfd-3ee1-4ac1-886a-39f05cc69a3e"
```suggestion
```

2022-11-23 20:18 UTC, jwscook commented on test/Project.toml
> +TableTransforms = "0d432bfd-3ee1-4ac1-886a-39f05cc69a3e"
Woops! Good catch.

2022-11-24 09:03 UTC, jwscook commented
> Thank you @jwscook for the PR ❤️ Regarding the initial guess, it is guaranteed to have norm 1. Do you have suggestions for the simplex size in this case?

I'm not entirely sure what the right size should be, but after some trial and error a value of 1/2 seems to work.

2022-11-24 11:06 UTC, juliohm commented on src/transforms/projectionpursuit.jl
> +  first(res)
```suggestion
  optimise(f, α₀, 1/2, xtol_rel=10eps()) |> first
```

2022-11-24 11:06 UTC, juliohm approved these changes

2022-11-24 11:08 UTC, juliohm commented
That is lovely @jwscook. I will just wait for the tests to pass once again and will then merge it. Did you consider moving NelderMead.jl to JuliaOptim or some other organization with multiple maintainers? It should get more visibility there. :)

2022-11-24 11:24 UTC, merged