WIP: Generalize the ColSpec interface
JuliaML/TableTransforms.jl pull request #29
Opened 2022-03-30 13:55 UTC by eliascarv

2022-03-30 16:52 UTC, juliohm commented on test/transforms.jl
> -    @test_throws ArgumentError Select()
What is the current meaning of Select() ?

2022-03-30 16:54 UTC, juliohm commented on src/transforms/utils.jl
> +_select(colspec::NTuple{N, <:ColSelector}, allcols) where {N} =
```suggestion
_select(colspec::NTuple{N,<:ColSelector}, allcols) where {N} =
```

2022-03-30 16:54 UTC, juliohm commented on src/transforms/utils.jl
> +const ColSpec = Union{Vector{T}, NTuple{N, T}, Regex, Colon} where {N, T<:ColSelector}
```suggestion
const ColSpec = Union{Vector{T}, NTuple{N,T}, Regex, Colon} where {N,T<:ColSelector}
```

2022-03-30 16:59 UTC, juliohm reviewed
It would be nice to document a bit further the utils.jl file so that first-time readers can figure out what is happening. Also, I left some comments on specific lines.

2022-03-31 18:06 UTC, juliohm requested changes
I believe that this PR is already mixing up too many things. If you can split it up in a PR with the minimum amount of changes to introduce a ColSpec type, we can then write separate PRs updating the Select/Reject, Rename, DropMissing, ...

2022-03-31 18:06 UTC, juliohm commented on src/transforms/colspec.jl
> +# second argument can be a Vector or Tuple
I believe that this comment section can be omitted, the code already provides this information.

2022-03-31 18:06 UTC, juliohm commented on src/transforms/colspec.jl
> +function _filter(colspec::Vector{Symbol}, allcols)
Please rename allcols to cols in all places

2022-03-31 18:55 UTC, eliascarv commented
I think I'll close this PR and make a new one that just adds the colspec.jl file without changing the Select, Revert and DropMissing.
What do you think?

2022-03-31 22:14 UTC, eliascarv commented
This PR will be closed and replaced with smaller PRs.

2022-03-31 22:14 UTC, closed without merging