Add pratio and maxdim
JuliaML/TableTransforms.jl pull request #89
Opened 2022-05-31 14:41 UTC by eliascarv

2022-05-31 17:53 UTC, juliohm requested changes
Hi @eliascarv I can give a more detailed review after 17hs BRT today. I wonder if we should preserve the semantic of ndim and use ndim and pratio as mutually exclusive options. That is what I had in mind originally.

Let's chat over Zulip to align detail later today.

2022-05-31 17:53 UTC, juliohm commented on src/transforms/eigenanalysis.jl
> +EigenAnalysis(proj; maxdim=nothing, pratio=0.99) =
Why not default 1?

2022-06-03 15:58 UTC, eliascarv commented on src/transforms/eigenanalysis.jl
> +EigenAnalysis(proj; maxdim=nothing, pratio=0.99) =
Because it's a statistical convention.

2022-06-03 18:43 UTC, juliohm requested changes
Review attached.

2022-06-03 18:43 UTC, juliohm commented on src/transforms/eigenanalysis.jl
> +`pratio` is the percentage ratio of the variances that will be preserved.
```suggestion
Optionally specify the maximum number of dimensions in the output `maxdim`
and the percentage of variance to retain `pratio`. Default to all dimensions of
the input.
```

2022-06-03 18:43 UTC, juliohm commented on src/transforms/eigenanalysis.jl
> +EigenAnalysis(:VDV, maxdim=3, pratio=0.89)
```suggestion
EigenAnalysis(:VD, pratio=0.99)
EigenAnalysis(:VDV, maxdim=3, pratio=0.99)
```

2022-06-03 18:48 UTC, juliohm approved these changes

2022-06-03 18:48 UTC, juliohm commented
Amazing PR as usual @eliascarv , super clean and professional coding 💯 Let's just wait for the tests to pass.

2022-06-03 19:00 UTC, merged