Add NarrowTypes
JuliaML/TableTransforms.jl pull request #96
Opened 2022-06-11 19:35 UTC by eliascarv

This PR implements NarrowTypes transform.

closes #75

2022-06-11 19:41 UTC, juliohm requested changes
🚀

2022-06-11 19:41 UTC, juliohm commented on src/TableTransforms.jl
> +  NarrowTypes,
Let's move this transform to before Coalesce

2022-06-13 16:24 UTC, eliascarv commented
This PR depends on fixing the following issue from the Transducers.jl package:
https://github.com/JuliaFolds/Transducers.jl/issues/524

2023-12-13 10:26 UTC, juliohm commented
Closing as discussed in #75

2023-12-13 10:26 UTC, closed without merging